-- MySQL Script generated by MySQL Workbench
-- vie 22 feb 2019 19:14:19 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema basesis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `basesis` ;

-- -----------------------------------------------------
-- Schema basesis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basesis` ;
USE `basesis` ;

-- -----------------------------------------------------
-- Table `basesis`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basesis`.`categorias` (
  `NombreCategoria` VARCHAR(75) NULL,
  `SalarioBaseCategoria` DOUBLE NULL DEFAULT 1,
  `ComplementoCategoria` DOUBLE NULL,
  `Idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basesis`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basesis`.`empresas` (
  `IdEmpresa` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `CIF` VARCHAR(10) NULL,
  PRIMARY KEY (`IdEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basesis`.`trabajadorbbdd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basesis`.`trabajadorbbdd` (
  `idTrabajador` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NULL,
  `Apellido1` VARCHAR(75) NULL,
  `Apellido2` VARCHAR(75) NULL,
  `NIFNIE` VARCHAR(10) NULL,
  `email` VARCHAR(75) NULL,
  `FechaAlta` DATE NULL,
  `CodigoCuenta` VARCHAR(20) NULL,
  `IBAN` VARCHAR(24) NULL,
  `IdEmpresa` INT(11) NULL,
  `IdCategoria` INT(11) NULL,
  PRIMARY KEY (`idTrabajador`),
  INDEX `fk_trabajadorbbdd_categorias_idx` (`IdCategoria` ASC),
  INDEX `fk_trabajadorbbdd_empresas1_idx` (`IdEmpresa` ASC),
  CONSTRAINT `fk_trabajadorbbdd_categorias`
    FOREIGN KEY (`IdCategoria`)
    REFERENCES `basesis`.`categorias` (`Idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajadorbbdd_empresas1`
    FOREIGN KEY (`IdEmpresa`)
    REFERENCES `basesis`.`empresas` (`IdEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basesis`.`nomina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basesis`.`nomina` (
  `IdNomina` INT(11) NOT NULL AUTO_INCREMENT COMMENT '		',
  `Mes` INT(11) NULL,
  `Anio` INT(11) NULL,
  `NumeroTrienios` INT(11) NULL,
  `ImporteTrienios` DOUBLE NULL,
  `importeSalarioMes` DOUBLE NULL,
  `importeComplementoMes` DOUBLE NULL,
  `ValorProrrateo` DOUBLE NULL,
  `brutoAnual` DOUBLE NULL,
  `IRPF` DOUBLE NULL,
  `ImporteIRPF` DOUBLE NULL,
  `BaseEmpresario` DOUBLE NULL,
  `SeguridadSocialEmpresario` DOUBLE NULL,
  `ImporteSeguridadSocialEmpresario` DOUBLE NULL,
  `DesempleoEmpresario` DOUBLE NULL,
  `ImporteDesempleoEmpresario` DOUBLE NULL,
  `FormacionEmpresario` DOUBLE NULL,
  `ImporteFormacionEmpresario` DOUBLE NULL,
  `AccidentesTrabajoEmpresario` DOUBLE NULL,
  `ImporteAccidentesTrabajoEmpresario` DOUBLE NULL,
  `FOGASAEmpresario` DOUBLE NULL,
  `ImporteFOGASAEmpresario` DOUBLE NULL,
  `SeguridadSocialTrabajador` DOUBLE NULL,
  `ImporteSeguridadSocialTrabajador` DOUBLE NULL,
  `DesempleoTrabajador` DOUBLE NULL,
  `ImporteDesempleoTrabajador` DOUBLE NULL,
  `FormacionTrabajador` DOUBLE NULL,
  `ImporteFormacionTrabajador` DOUBLE NULL,
  `BrutoNomina` DOUBLE NULL,
  `LiquidoNomina` DOUBLE NULL,
  `CosteTotalEmpresario` DOUBLE NULL,
  `IdTrabajador` INT(11) NULL,
  PRIMARY KEY (`IdNomina`),
  INDEX `fk_nomina_trabajadorbbdd1_idx` (`IdTrabajador` ASC),
  CONSTRAINT `fk_nomina_trabajadorbbdd1`
    FOREIGN KEY (`IdTrabajador`)
    REFERENCES `basesis`.`trabajadorbbdd` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
